# Generated by Django 5.0.4 on 2024-04-30 00:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Officials',
            new_name='Official',
        ),
        migrations.AddField(
            model_name='social',
            name='official_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='server.official'),
            preserve_default=False,
        ),
    ]
