# Generated by Django 5.0.4 on 2024-04-30 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_rename_officials_official_social_official_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='official',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.official_position'),
        ),
        migrations.CreateModel(
            name='Official_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('website', models.URLField()),
                ('github', models.URLField()),
                ('discord', models.URLField()),
                ('linkedin', models.URLField()),
                ('social', models.URLField(choices=[('website', 'Website'), ('github', 'Github'), ('discord', 'Discord'), ('linkedin', 'Linkedin')])),
                ('official_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.official')),
            ],
        ),
        migrations.AlterField(
            model_name='official',
            name='social_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.official_social'),
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
