# Generated by Django 5.0.4 on 2024-04-30 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_official_position_alter_official_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='social_id',
        ),
        migrations.RemoveField(
            model_name='official_social',
            name='id',
        ),
        migrations.AlterField(
            model_name='official_social',
            name='official_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server.official'),
        ),
    ]
