# Generated by Django 5.0.4 on 2024-04-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_official_social_id_remove_official_social_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='official_social',
            old_name='discord',
            new_name='URL',
        ),
        migrations.RemoveField(
            model_name='official_social',
            name='github',
        ),
        migrations.RemoveField(
            model_name='official_social',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='official_social',
            name='website',
        ),
    ]
