# Generated by Django 5.0.4 on 2024-04-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_rename_discord_official_social_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official_social',
            name='social',
            field=models.CharField(choices=[('website', 'Website'), ('github', 'Github'), ('discord', 'Discord'), ('linkedin', 'Linkedin')], max_length=200),
        ),
    ]
