# Generated by Django 5.0.4 on 2024-05-22 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_address_alter_event_description_alter_event_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='media_id',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='album_id',
            new_name='album',
        ),
    ]
