# Generated by Django 5.0.4 on 2024-05-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_rename_media_id_album_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='media',
        ),
        migrations.AddField(
            model_name='album',
            name='media',
            field=models.ManyToManyField(to='server.media'),
        ),
    ]
