# Generated by Django 5.0.4 on 2024-05-22 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_remove_album_media_album_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.media'),
        ),
    ]
