# Generated by Django 5.0.4 on 2024-05-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_alter_album_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='media',
        ),
    ]
