# Generated by Django 5.0.4 on 2024-05-22 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_remove_album_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='media',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='server.media'),
            preserve_default=False,
        ),
    ]
