# Generated by Django 5.0.4 on 2024-05-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_remove_album_media_media_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='media',
            field=models.ManyToManyField(to='server.media'),
        ),
    ]
